#ifndef _EVENTS_75D0CC67_0F38_4255_9DF5_F7D49E4BFE24_
#define _EVENTS_75D0CC67_0F38_4255_9DF5_F7D49E4BFE24_

#ifdef _DEBUG
#define DBGTRACEEVENT(x) DbgTraceWinEvents(x)

void DbgTraceWinEvents(DWORD dwEvent)
{
	switch(dwEvent)
	{
		//https://msdn.microsoft.com/en-us/library/windows/desktop/dd318066(v=vs.85).aspx

		//case EVENT_SYSTEM_SWITCHSTART: OutputDebugString(L"EVENT_SYSTEM_SWITCHSTART\n");break;
		//case EVENT_SYSTEM_SWITCHEND: OutputDebugString(L"EVENT_SYSTEM_SWITCHEND\n");break;
		//case EVENT_SYSTEM_SOUND: OutputDebugString(L"EVENT_SYSTEM_SOUND\n");break;
		//case EVENT_SYSTEM_SCROLLINGSTART: OutputDebugString(L"EVENT_SYSTEM_SCROLLINGSTART\n");break;
		//case EVENT_SYSTEM_SCROLLINGEND: OutputDebugString(L"EVENT_SYSTEM_SCROLLINGEND\n");break;
		case EVENT_SYSTEM_MOVESIZESTART: OutputDebugString(L"EVENT_SYSTEM_MOVESIZESTART\n");break;
		case EVENT_SYSTEM_MOVESIZEEND: OutputDebugString(L"EVENT_SYSTEM_MOVESIZEEND\n");break;
		case EVENT_SYSTEM_MINIMIZESTART: OutputDebugString(L"EVENT_SYSTEM_MINIMIZESTART\n");break;
		case EVENT_SYSTEM_MINIMIZEEND: OutputDebugString(L"EVENT_SYSTEM_MINIMIZEEND\n");break;
		//case EVENT_SYSTEM_MENUSTART: OutputDebugString(L"EVENT_SYSTEM_MENUSTART\n");break;
		//case EVENT_SYSTEM_MENUPOPUPSTART: OutputDebugString(L"EVENT_SYSTEM_MENUPOPUPSTART\n");break;
		//case EVENT_SYSTEM_MENUPOPUPEND: OutputDebugString(L"EVENT_SYSTEM_MENUPOPUPEND\n");break;
		//case EVENT_SYSTEM_MENUEND: OutputDebugString(L"EVENT_SYSTEM_MENUEND\n");break;
		//case EVENT_SYSTEM_FOREGROUND: OutputDebugString(L"EVENT_SYSTEM_FOREGROUND\n");break;
		////case EVENT_SYSTEM_END: OutputDebugString(L"EVENT_SYSTEM_END\n");break;
		//case EVENT_SYSTEM_DRAGDROPSTART: OutputDebugString(L"EVENT_SYSTEM_DRAGDROPSTART\n");break;
		//case EVENT_SYSTEM_DRAGDROPEND: OutputDebugString(L"EVENT_SYSTEM_DRAGDROPEND\n");break;
		//case EVENT_SYSTEM_DIALOGSTART: OutputDebugString(L"EVENT_SYSTEM_DIALOGSTART\n");break;
		//case EVENT_SYSTEM_DIALOGEND: OutputDebugString(L"EVENT_SYSTEM_DIALOGEND\n");break;
		////case EVENT_SYSTEM_DESKTOPSWITCH: OutputDebugString(L"EVENT_SYSTEM_DESKTOPSWITCH\n");break;
		//case EVENT_SYSTEM_CONTEXTHELPSTART: OutputDebugString(L"EVENT_SYSTEM_CONTEXTHELPSTART\n");break;
		//case EVENT_SYSTEM_CONTEXTHELPEND: OutputDebugString(L"EVENT_SYSTEM_CONTEXTHELPEND\n");break;
		//case EVENT_SYSTEM_CAPTURESTART: OutputDebugString(L"EVENT_SYSTEM_CAPTURESTART\n");break;
		//case EVENT_SYSTEM_CAPTUREEND: OutputDebugString(L"EVENT_SYSTEM_CAPTUREEND\n");break;
		////case EVENT_SYSTEM_ARRANGMENTPREVIEW: OutputDebugString(L"EVENT_SYSTEM_ARRANGMENTPREVIEW\n");break;
		//case EVENT_SYSTEM_ALERT: OutputDebugString(L"EVENT_SYSTEM_ALERT\n");break;
		//case EVENT_OBJECT_VALUECHANGE: OutputDebugString(L"EVENT_OBJECT_VALUECHANGE\n");break;
		//////case EVENT_OBJECT_UNCLOAKED: OutputDebugString(L"EVENT_OBJECT_UNCLOAKED\n");break;
		////case EVENT_OBJECT_TEXTSELECTIONCHANGED: OutputDebugString(L"EVENT_OBJECT_TEXTSELECTIONCHANGED\n");break;
		//////case EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED: OutputDebugString(L"EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED\n");break;
		//case EVENT_OBJECT_STATECHANGE: OutputDebugString(L"EVENT_OBJECT_STATECHANGE\n");break;
		case EVENT_OBJECT_SHOW: OutputDebugString(L"EVENT_OBJECT_SHOW\n");break;
		//case EVENT_OBJECT_SELECTIONWITHIN: OutputDebugString(L"EVENT_OBJECT_SELECTIONWITHIN\n");break;
		//case EVENT_OBJECT_SELECTIONREMOVE: OutputDebugString(L"EVENT_OBJECT_SELECTIONREMOVE\n");break;
		//case EVENT_OBJECT_SELECTIONADD: OutputDebugString(L"EVENT_OBJECT_SELECTIONADD\n");break;
		//case EVENT_OBJECT_SELECTION: OutputDebugString(L"EVENT_OBJECT_SELECTION\n");break;
		//case EVENT_OBJECT_REORDER: OutputDebugString(L"EVENT_OBJECT_REORDER\n");break;
		//case EVENT_OBJECT_PARENTCHANGE: OutputDebugString(L"EVENT_OBJECT_PARENTCHANGE\n");break;
		//case EVENT_OBJECT_NAMECHANGE: OutputDebugString(L"EVENT_OBJECT_NAMECHANGE\n");break;
		//case EVENT_OBJECT_LOCATIONCHANGE: OutputDebugString(L"EVENT_OBJECT_LOCATIONCHANGE\n");break;
		//////case EVENT_OBJECT_LIVEREGIONCHANGED: OutputDebugString(L"EVENT_OBJECT_LIVEREGIONCHANGED\n");break;
		////case EVENT_OBJECT_INVOKED: OutputDebugString(L"EVENT_OBJECT_INVOKED\n");break;
		//////case EVENT_OBJECT_IME_SHOW: OutputDebugString(L"EVENT_OBJECT_IME_SHOW\n");break;
		//////case EVENT_OBJECT_IME_HIDE: OutputDebugString(L"EVENT_OBJECT_IME_HIDE\n");break;
		//////case EVENT_OBJECT_IME_CHANGE: OutputDebugString(L"EVENT_OBJECT_IME_CHANGE\n");break;
		//////case EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED: OutputDebugString(L"EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED\n");break;
		case EVENT_OBJECT_HIDE: OutputDebugString(L"EVENT_OBJECT_HIDE\n");break;
		//case EVENT_OBJECT_HELPCHANGE: OutputDebugString(L"EVENT_OBJECT_HELPCHANGE\n");break;
		//case EVENT_OBJECT_FOCUS: OutputDebugString(L"EVENT_OBJECT_FOCUS\n");break;
		////case EVENT_OBJECT_END: OutputDebugString(L"EVENT_OBJECT_END\n");break;
		//////case EVENT_OBJECT_DRAGSTART: OutputDebugString(L"EVENT_OBJECT_DRAGSTART\n");break;
		//////case EVENT_OBJECT_DRAGLEAVE: OutputDebugString(L"EVENT_OBJECT_DRAGLEAVE\n");break;
		//////case EVENT_OBJECT_DRAGENTER: OutputDebugString(L"EVENT_OBJECT_DRAGENTER\n");break;
		//////case EVENT_OBJECT_DRAGDROPPED: OutputDebugString(L"EVENT_OBJECT_DRAGDROPPED\n");break;
		//////case EVENT_OBJECT_DRAGCOMPLETE: OutputDebugString(L"EVENT_OBJECT_DRAGCOMPLETE\n");break;
		//////case EVENT_OBJECT_DRAGCANCEL: OutputDebugString(L"EVENT_OBJECT_DRAGCANCEL\n");break;
		case EVENT_OBJECT_DESTROY: OutputDebugString(L"EVENT_OBJECT_DESTROY\n");break;
		//case EVENT_OBJECT_DESCRIPTIONCHANGE: OutputDebugString(L"EVENT_OBJECT_DESCRIPTIONCHANGE\n");break;
		//case EVENT_OBJECT_DEFACTIONCHANGE: OutputDebugString(L"EVENT_OBJECT_DEFACTIONCHANGE\n");break;
		//case EVENT_OBJECT_CREATE: OutputDebugString(L"EVENT_OBJECT_CREATE\n");break;
		////case EVENT_OBJECT_CONTENTSCROLLED: OutputDebugString(L"EVENT_OBJECT_CONTENTSCROLLED\n");break;
		//////case EVENT_OBJECT_CLOAKED: OutputDebugString(L"EVENT_OBJECT_CLOAKED\n");break;
		//case EVENT_OBJECT_ACCELERATORCHANGE: OutputDebugString(L"EVENT_OBJECT_ACCELERATORCHANGE\n");break;
		////case EVENT_OEM_DEFINED_START: OutputDebugString(L"EVENT_OEM_DEFINED_START\n");break;
		////case EVENT_OEM_DEFINED_END: OutputDebugString(L"EVENT_OEM_DEFINED_END\n");break;
    }
}

#else
#define DBGTRACEEVENT(x)
#endif

#endif//_EVENTS_75D0CC67_0F38_4255_9DF5_F7D49E4BFE24_
